import React from 'react';
import { Provenance } from '../../types/api';

interface ProvenanceBadgeProps {
  provenance: Provenance | string;
  className?: string;
  showTooltip?: boolean;
}

export const ProvenanceBadge: React.FC<ProvenanceBadgeProps> = ({
  provenance,
  className = '',
  showTooltip = true,
}) => {
  const getBadgeStyle = (prov: string) => {
    switch (prov) {
      case 'SIMULATED':
        return 'bg-blue-950/80 text-blue-400 border-blue-800/60';
      case 'OBSERVED':
        return 'bg-emerald-950/80 text-emerald-400 border-emerald-800/60';
      case 'ESTIMATED':
        return 'bg-amber-950/80 text-amber-400 border-amber-800/60';
      case 'MODEL':
        return 'bg-purple-950/80 text-purple-400 border-purple-800/60';
      case 'CALCULATED':
        return 'bg-cyan-950/80 text-cyan-400 border-cyan-800/60';
      case 'LLM':
        return 'bg-rose-950/80 text-rose-400 border-rose-800/60';
      default:
        return 'bg-slate-900 text-slate-400 border-slate-700';
    }
  };

  const getTooltipText = (prov: string) => {
    switch (prov) {
      case 'SIMULATED':
        return 'Ground truth physical state generated by pandapower digital twin';
      case 'OBSERVED':
        return 'Raw RTU telemetry as received over simulated SCADA channel (with noise)';
      case 'ESTIMATED':
        return 'State computed by WLS state estimator from observable measurements';
      case 'MODEL':
        return 'Trained Machine Learning model inference (Isolation Forest / HistGradientBoosting)';
      case 'CALCULATED':
        return 'Deterministic formula / policy evaluation without learned parameters';
      case 'LLM':
        return 'Generative AI synthesis strictly grounded in structured context';
      default:
        return prov;
    }
  };

  return (
    <span
      title={showTooltip ? getTooltipText(provenance) : undefined}
      className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-mono font-medium border uppercase tracking-wider ${getBadgeStyle(
        provenance
      )} ${className}`}
    >
      {provenance}
    </span>
  );
};
