import React, { useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { ShieldCheck, KeyRound, User, Lock, AlertTriangle, CheckCircle2 } from 'lucide-react';

interface BootstrapModalProps {
  isOpen: boolean;
  onSuccess: () => void;
}

export const BootstrapModal: React.FC<BootstrapModalProps> = ({ isOpen, onSuccess }) => {
  const { bootstrap, bootstrapTokenHint } = useAuth();
  const [token, setToken] = useState(bootstrapTokenHint || '');
  const [username, setUsername] = useState('admin');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [displayName, setDisplayName] = useState('System Administrator');
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    if (password.length < 8) {
      setError('Password must be at least 8 characters long.');
      return;
    }
    if (password !== confirmPassword) {
      setError('Passwords do not match.');
      return;
    }
    if (!token.trim()) {
      setError('Bootstrap token is required.');
      return;
    }

    try {
      setLoading(true);
      await bootstrap(username.trim(), password, token.trim(), displayName.trim());
      onSuccess();
    } catch (err: any) {
      setError(err.message || 'Bootstrap initialization failed.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4">
      <div className="bg-surface border border-border rounded w-full max-w-md overflow-hidden shadow-sm">
        <div className="bg-panel-alt p-5 border-b border-border flex items-center gap-3">
          <div className="w-10 h-10 rounded bg-blue-600/20 border border-blue-500/40 flex items-center justify-center text-blue-400">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-base font-bold text-text-main">First-Run System Setup</h2>
            <p className="text-xs text-text-muted">Initialize the primary administrator account</p>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-5 space-y-4">
          {error && (
            <div className="p-3 bg-red-900/30 border border-red-500/50 rounded flex items-center gap-2 text-xs text-red-200">
              <AlertTriangle className="w-4 h-4 text-red-400 shrink-0" />
              <span>{error}</span>
            </div>
          )}

          <div className="space-y-1">
            <label className="text-xs font-semibold text-text-muted flex items-center gap-1.5">
              <KeyRound className="w-3.5 h-3.5 text-blue-400" />
              One-Time Bootstrap Token
            </label>
            <input
              type="text"
              value={token}
              onChange={(e) => setToken(e.target.value)}
              placeholder="Paste token generated by server"
              required
              className="w-full bg-app border border-border-main rounded px-3 py-2 text-xs text-text-main focus:outline-none focus:border-blue-500 font-mono"
            />
            <p className="text-[10px] text-text-muted">
              Auto-generated during initialization. Printed to backend logs on startup.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-semibold text-text-muted flex items-center gap-1.5">
                <User className="w-3.5 h-3.5 text-blue-400" />
                Username
              </label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                required
                className="w-full bg-app border border-border-main rounded px-3 py-2 text-xs text-text-main focus:outline-none focus:border-blue-500"
              />
            </div>
            <div className="space-y-1">
              <label className="text-xs font-semibold text-text-muted">Display Name</label>
              <input
                type="text"
                value={displayName}
                onChange={(e) => setDisplayName(e.target.value)}
                className="w-full bg-app border border-border-main rounded px-3 py-2 text-xs text-text-main focus:outline-none focus:border-blue-500"
              />
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-text-muted flex items-center gap-1.5">
              <Lock className="w-3.5 h-3.5 text-blue-400" />
              Admin Password (min. 8 characters)
            </label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••••••"
              required
              minLength={8}
              className="w-full bg-app border border-border-main rounded px-3 py-2 text-xs text-text-main focus:outline-none focus:border-blue-500"
            />
          </div>

          <div className="space-y-1">
            <label className="text-xs font-semibold text-text-muted">Confirm Password</label>
            <input
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              placeholder="••••••••••••"
              required
              className="w-full bg-app border border-border-main rounded px-3 py-2 text-xs text-text-main focus:outline-none focus:border-blue-500"
            />
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full mt-2 bg-blue-600 hover:bg-blue-500 text-white font-semibold py-2 px-4 rounded text-xs transition-colors flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
          >
            {loading ? (
              <span>Initializing Secure Core...</span>
            ) : (
              <>
                <CheckCircle2 className="w-4 h-4" />
                Initialize System & Sign In
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
};
