"""
GridShield AI — After-Action Report & Evidence Bundle Exporter (Task 4.4).

Generates structured after-action evidence reports in JSON and Markdown/PDF formats.

Includes:
- Incident summary & timeline
- Environment label & full version registry
- 5D Confidence Vector & evidence object breakdown
- Product Boundary Disclaimer
"""
import json
from typing import Dict, Any, Optional
from datetime import datetime, timezone

class ReportExporter:
    """
    After-Action Report exporter for Exercise & Analysis modes.
    """
    @staticmethod
    def generate_after_action_report(evidence_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate JSON After-Action Report bundle.
        """
        report_id = f"AAR_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
        
        return {
            "report_id": report_id,
            "title": "GridShield AI After-Action Evidence & Analysis Report",
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "disclaimer": (
                "GridShield AI detects, attributes, simulates, recommends, and explains. "
                "It does not guarantee safety, detection, or grid stability; operate the grid; "
                "replace protection systems or operators; or certify compliance. "
                "Simulated results are never presented as real-world performance."
            ),
            "environment": evidence_data.get("environment", "SIMULATOR"),
            "provenance": evidence_data.get("provenance", "SIMULATED"),
            "evidence_bundle": evidence_data,
            "export_version": "v1.0"
        }

    @staticmethod
    def export_to_markdown(report: Dict[str, Any]) -> str:
        """
        Render After-Action Report as structured Markdown document.
        """
        lines = [
            f"# {report['title']}",
            f"**Report ID**: {report['report_id']} | **Timestamp**: {report['timestamp']}",
            f"**Environment**: `{report['environment']}` | **Provenance**: `{report['provenance']}`",
            "",
            "---",
            "## Product Boundary Disclaimer",
            f"> {report['disclaimer']}",
            "",
            "---",
            "## Evidence Bundle Details",
            "```json",
            json.dumps(report["evidence_bundle"], indent=2),
            "```",
            "",
            "---",
            "*Generated by GridShield AI Workbench.*"
        ]
        return "\n".join(lines)
